import {
  agora,
  bancoDoBrasil,
  binance,
  bradesco,
  btg,
  btgInvest,
  c6,
  caixa,
  clear,
  foxbit,
  inter,
  itau,
  mercadoBitcoin,
  nubank,
  nuInvest,
  rico,
  santander,
  xp,
  orama,
  ativa,
  avenue,
  banrisul,
  bmg,
  bv,
  daycoval,
  iti,
  mercadopago,
  modalmais,
  n26,
  neon,
  next,
  pagbank,
  pan,
  pb,
  picpay,
  sicoob,
  sofisa,
  toro,
  wise,
  nomad,
  revolut,
  will,
} from 'assets';
import money from 'assets/categories/money.svg';
import piggyBank from 'assets/categories/piggy-bank.svg';

export const category = [
  {
    icon: money,
    name: 'Dinheiro',
    category: 'cash',
  },
  {
    icon: bradesco,
    name: 'Bradesco',
    category: 'bank',
  },
  {
    icon: bancoDoBrasil,
    name: 'Banco do Brasil',
    category: 'bank',
  },
  {
    icon: santander,
    name: 'Santander',
    category: 'bank',
  },
  {
    icon: itau,
    name: 'Itaú',
    category: 'bank',
  },
  {
    icon: caixa,
    name: 'Caixa',
    category: 'bank',
  },
  {
    icon: nubank,
    name: 'NuConta',
    category: 'bank',
  },
  {
    icon: c6,
    name: 'C6Bank',
    category: 'bank',
  },
  {
    icon: inter,
    name: 'Inter',
    category: 'bank',
  },
  {
    icon: btg,
    name: 'BTG Pactual',
    category: 'bank',
  },
  {
    icon: nuInvest,
    name: 'NuInvest',
    category: 'investments',
  },
  {
    icon: c6,
    name: 'C6 Investimentos',
    category: 'investments',
  },
  {
    icon: inter,
    name: 'Inter Investimentos',
    category: 'investments',
  },
  {
    icon: xp,
    name: 'XP Investimentos',
    category: 'investments',
  },
  {
    icon: clear,
    name: 'Clear Investimentos',
    category: 'investments',
  },
  {
    icon: btgInvest,
    name: 'BTG Investimentos',
    category: 'investments',
  },
  {
    icon: rico,
    name: 'Rico Investimentos',
    category: 'investments',
  },
  {
    icon: agora,
    name: 'Ágora Investimentos',
    category: 'investments',
  },
  {
    icon: orama,
    name: 'Órama Investimentos',
    category: 'investments',
  },
  {
    icon: binance,
    name: 'Binance',
    category: 'crypto',
  },
  {
    icon: mercadoBitcoin,
    name: 'Mercado Bitcoin',
    category: 'crypto',
  },
  {
    icon: foxbit,
    name: 'Foxbit',
    category: 'crypto',
  },
  {
    icon: ativa,
    name: 'Ativa Investimentos',
    category: 'investments',
  },
  {
    icon: avenue,
    name: 'Avenue Investimentos',
    category: 'investments',
  },
  {
    icon: banrisul,
    name: 'Banrisul',
    category: 'bank',
  },
  {
    icon: bmg,
    name: 'BMG',
    category: 'bank',
  },
  {
    icon: bv,
    name: 'BV',
    category: 'bank',
  },
  {
    icon: daycoval,
    name: 'Daycoval',
    category: 'bank',
  },
  {
    icon: iti,
    name: 'Iti',
    category: 'bank',
  },
  {
    icon: mercadopago,
    name: 'Mercado Pago',
    category: 'bank',
  },
  {
    icon: modalmais,
    name: 'Modal Mais',
    category: 'bank',
  },
  {
    icon: n26,
    name: 'N26',
    category: 'bank',
  },
  {
    icon: neon,
    name: 'Neon',
    category: 'bank',
  },
  {
    icon: next,
    name: 'Next',
    category: 'bank',
  },
  {
    icon: pagbank,
    name: 'PagBank',
    category: 'bank',
  },
  {
    icon: pan,
    name: 'Pan',
    category: 'bank',
  },
  {
    icon: pb,
    name: 'Players Bank',
    category: 'bank',
  },
  {
    icon: picpay,
    name: 'PicPay',
    category: 'bank',
  },
  {
    icon: sicoob,
    name: 'Sicoob',
    category: 'bank',
  },
  {
    icon: sofisa,
    name: 'Sofisa',
    category: 'bank',
  },
  {
    icon: toro,
    name: 'Toro Investimentos',
    category: 'investments',
  },
  {
    icon: wise,
    name: 'Wise',
    category: 'bank',
  },
  {
    icon: nomad,
    name: 'Nomad',
    category: 'bank',
  },
  {
    icon: revolut,
    name: 'Revolut',
    category: 'bank',
  },
  {
    icon: will,
    name: 'Will Bank',
    category: 'bank',
  },
  {
    icon: piggyBank,
    name: 'Rendimentos',
    category: 'savings',
  },
];
