name: Semantic Versioning

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Fix Lint
        run: yarn lint
      - name: Build app
        run: yarn build
      - name: Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    if: success('publish')
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
